version: 2

models:
  - name: facebook_ads__base_spend
    description: |
      Essential Facebook Ads spend tracking with core performance metrics at daily ad level.
      
      **Business Purpose:** Core spend analysis and ROI tracking for campaign budget management
      and performance evaluation.
      
      **Data Grain:** One record per ad per day
      
      **Usage Examples:**
      - Daily spend analysis and budget tracking
      - Campaign ROI reporting and optimization
      - Cost efficiency monitoring across campaigns
      - Budget allocation planning and forecasting
      
      **Data Freshness:** Updated daily with previous day's performance data
      
      **Dependencies:** Sources from int_facebook_ads__daily_metrics with enhanced data quality validation
    
    columns:
      - name: date_day
        description: "Date of the advertising activity (YYYY-MM-DD format)"
        tests:
          - not_null
      
      - name: campaign_name
        description: "Name of the Facebook advertising campaign"
        tests:
          - not_null
      
      - name: ad_name
        description: "Name of the specific advertisement within the campaign"
        tests:
          - not_null
      
      - name: impressions
        description: "Total number of times the ad was displayed to users"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
      
      - name: clicks
        description: "Total number of clicks received on the advertisement"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
      
      - name: spend
        description: "Total amount spent on the advertisement in USD"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      
      - name: conversions
        description: "Total number of desired actions completed (purchases, sign-ups, etc.)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
      
      - name: objective
        description: "Campaign goal or purpose (e.g., conversions, traffic, brand awareness)"
        tests:
          - accepted_values:
              values: ['Lead Generation', 'Conversions', 'Traffic', 'Brand Awareness', 'Reach', 'Video Views', 'Messages', 'App Installs', 'Event Responses', 'Link Clicks', 'Local Awareness', 'Offer Claims', 'Page Likes', 'Post Engagement', 'Product Catalog Sales', 'Store Visits', 'Unknown']
      
      - name: account_id
        description: "Unique identifier for the Facebook Ads account"
        tests:
          - not_null
      
      - name: click_through_rate
        description: "Percentage of impressions that resulted in clicks (clicks/impressions * 100)"
      
      - name: cost_per_click
        description: "Average cost paid for each click (spend/clicks)"
      
      - name: cost_per_conversion
        description: "Average cost paid for each conversion (spend/conversions)"
      
      - name: return_on_ad_spend
        description: "Revenue generated per dollar spent on advertising (conversion_value/spend)"

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - date_day
            - account_id
            - campaign_name
            - ad_name
      - dbt_utils.expression_is_true:
          expression: "clicks <= impressions"
          config:
            where: "impressions > 0"

  - name: facebook_ads__ad_performance_daily
    description: |
      Daily Facebook Ads performance metrics for analysis and optimization.
      
      **Business Purpose:** Performance analysis enabling data driven campaign optimization,
      A/B testing insights, and reporting across all advertising metrics.
      
      **Data Grain:** One record per ad per day with complete metric suite including performance
      classifications and alert flags.
      
      **Usage Examples:**
      - Performance optimization and campaign tuning
      - A/B testing analysis and statistical insights
      - Executive and stakeholder reporting
      - Performance monitoring and alerting
      - Cross campaign benchmarking and analysis
      
      **Data Freshness:** Updated daily with previous day's performance data
      
      **Dependencies:** Sources from int_facebook_ads__daily_metrics with enhanced data quality validation
    
    columns:
      - name: date_day
        description: "Date of the advertising activity (YYYY-MM-DD format)"
        tests:
          - not_null
      
      - name: account_id
        description: "Unique identifier for the Facebook Ads account"
        tests:
          - not_null
      
      - name: account_name
        description: "Human-readable name of the Facebook Ads account"
      
      - name: campaign_id
        description: "Unique identifier for the Facebook advertising campaign"
        tests:
          - not_null
      
      - name: campaign_name
        description: "Name of the Facebook advertising campaign"
      
      - name: campaign_objective
        description: "Campaign goal or purpose (e.g., conversions, traffic, brand awareness)"
      
      - name: campaign_status
        description: "Current status of the campaign (Active, Paused, etc.)"
      
      - name: ad_id
        description: "Unique identifier for the specific advertisement"
        tests:
          - not_null
      
      - name: ad_name
        description: "Name of the specific advertisement within the campaign"
      
      - name: impressions
        description: "Total number of times the ad was displayed to users"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
      
      - name: clicks
        description: "Total number of clicks received on the advertisement"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
      
      - name: spend
        description: "Total amount spent on the advertisement in USD"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
      
      - name: reach
        description: "Number of unique users who saw the advertisement"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
      
      - name: frequency
        description: "Average number of times each person saw the ad (impressions/reach)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
      
      - name: conversions
        description: "Total number of desired actions completed (purchases, sign-ups, etc.)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
      
      - name: conversion_value
        description: "Total monetary value of conversions in USD"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
      
      - name: click_through_rate
        description: "Percentage of impressions that resulted in clicks (clicks/impressions * 100)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      
      - name: cost_per_click
        description: "Average cost paid for each click (spend/clicks)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
      
      - name: cost_per_mille
        description: "Cost per thousand impressions (spend/impressions * 1000)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
      
      - name: conversion_rate
        description: "Percentage of clicks that resulted in conversions (conversions/clicks * 100)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      
      - name: return_on_ad_spend
        description: "Revenue generated per dollar spent on advertising (conversion_value/spend)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
      
      - name: cost_per_conversion
        description: "Average cost paid for each conversion (spend/conversions)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
      
      - name: performance_tier
        description: "Performance classification based on efficiency metrics and benchmarks"
        tests:
          - accepted_values:
              values: ['High Performer', 'Good Performer', 'Average Performer', 'Poor Performer', 'No Spend']
      
      - name: metric_alert_flag
        description: "Boolean flag indicating if performance metrics require attention or review"

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - date_day
            - account_id
            - campaign_id
            - ad_id
      - dbt_utils.expression_is_true:
          expression: "clicks <= impressions"
          config:
            where: "impressions > 0"
      - dbt_utils.expression_is_true:
          expression: "click_through_rate <= 100"
          config:
            where: "click_through_rate is not null"