version: 2

models:
  - name: stg_facebook_ads__insights
    description: Cleaned and standardized Facebook Ads performance data from Windsor.ai with data quality filtering
    columns:
      - name: date_day
        description: Report date for the advertising metrics
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: "'2020-01-01'"
              max_value: "current_date()"

      - name: account_id
        description: Facebook Ad Account ID - unique identifier for the advertising account
        tests:
          - not_null

      - name: account_name
        description: Business Manager account name - human-readable account identifier
        tests:
          - not_null

      - name: campaign_id
        description: Facebook Campaign ID - unique identifier for the campaign
        tests:
          - not_null

      - name: campaign_name
        description: Campaign name - human-readable campaign identifier
        tests:
          - not_null

      - name: campaign_objective
        description: Standardized Facebook campaign objective (Lead Generation, Conversions, etc.)
        tests:
          - accepted_values:
              values: ['Outcome Traffic', 'Lead Generation', 'Conversions', 'Brand Awareness']

      - name: campaign_status
        description: Current status of the campaign
        tests:
          - accepted_values:
              values: ['ACTIVE', 'PAUSED', 'ARCHIVED', 'DELETED']

      - name: ad_id
        description: Facebook Ad ID - unique identifier for the individual ad
        tests:
          - not_null

      - name: ad_name
        description: Ad name - human-readable ad identifier

      - name: impressions
        description: Number of times the ad was displayed
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

      - name: clicks
        description: Number of clicks on the ad
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

      - name: spend
        description: Amount spent on the ad in account currency
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

      - name: reach
        description: Number of unique users who saw the ad
        tests:
          - dbt_utils.accepted_range:
              min_value: 0

      - name: frequency
        description: Average number of times each user saw the ad (impressions/reach)
        tests:
          - dbt_utils.accepted_range:
              min_value: 0

      - name: cost_per_mille
        description: Cost per 1000 impressions (CPM)
        tests:
          - dbt_utils.accepted_range:
              min_value: 0

      - name: cost_per_click
        description: Average cost per click (CPC)
        tests:
          - dbt_utils.accepted_range:
              min_value: 0

      - name: click_through_rate
        description: Click-through rate as percentage (clicks/impressions * 100)
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100

      - name: conversions
        description: Number of purchase conversions attributed to the ad
        tests:
          - dbt_utils.accepted_range:
              min_value: 0

      - name: conversion_value
        description: Total value of purchase conversions in account currency
        tests:
          - dbt_utils.accepted_range:
              min_value: 0

      - name: cost_per_conversion
        description: Average cost per conversion (spend/conversions)
        tests:
          - dbt_utils.accepted_range:
              min_value: 0

      - name: return_on_ad_spend
        description: Return on ad spend ratio (conversion_value/spend)
        tests:
          - dbt_utils.accepted_range:
              min_value: 0

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - date_day
            - account_id
            - campaign_id
            - ad_id
      - dbt_utils.expression_is_true:
          expression: "clicks <= impressions or impressions is null"
      - dbt_utils.expression_is_true:
          expression: "reach <= impressions or reach is null or impressions is null"