version: 2

sources:
  - name: raw_data
    description: Raw Facebook Ads data from Windsor.ai
    database: windsor-dbt-development
    schema: raw_data
    tables:
      - name: facebook_ads_windsor_real
        description: Raw Facebook Ads performance data from Windsor.ai integration
        columns:
          - name: date
            description: Report date
          - name: account_id
            description: Facebook Ad Account ID
          - name: account_name
            description: Business Manager account name
          - name: campaign_id
            description: Facebook Campaign ID
          - name: campaign
            description: Campaign name
          - name: campaign_objective
            description: Facebook campaign objective
          - name: campaign_status
            description: Campaign status
          - name: ad_id
            description: Facebook Ad ID
          - name: ad_name
            description: Ad name
          - name: impressions
            description: Number of impressions
          - name: clicks
            description: Number of clicks
          - name: spend
            description: Amount spent in account currency
          - name: reach
            description: Unique users reached
          - name: frequency
            description: Average impressions per user
          - name: cpm
            description: Cost per 1000 impressions
          - name: cpc
            description: Cost per click
          - name: ctr
            description: Click-through rate (%)
          - name: actions_purchase
            description: Total purchase conversions
          - name: action_values_purchase
            description: Total purchase conversion value